name: Release and Publish

on:
  push:
    branches:
      - 'master'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Set Dynamic Version
        run: |
          PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          BASE_VERSION=$(echo $PROJECT_VERSION | cut -d'-' -f1)
          NEW_VERSION="${BASE_VERSION}.${{ github.run_number }}"
          echo "Project version set to: $NEW_VERSION"
          mvn versions:set -DnewVersion=$NEW_VERSION

      - name: Build and Deploy to GitHub Packages
        run: mvn -B deploy --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
